#GETTING AN BASE OS
FROM openjdk:11-jre-slim

#SET THE WORK DIRECTORY 
WORKDIR /apk

#COPYING THE JAR FILE TO OUR FOLDER
COPY target/my-maven-project-1.0-SNAPSHOT.jar /apk/java-1.0-SNAPSHOT.jar

#ATTACHING PORT TO THE CONTAINER TO ACCES
EXPOSE 87

#PASSING COMMAND IN DOCKERFILE
CMD [ "java", "-jar", "my-maven-project-1.0-SNAPSHOT.jar" ]

